### ISSUE TITLE
Conflict with FireFTP

### ISSUE THREAD

**Issue by Pheil** [evilpie/404-bookmarks#1]
Version 1.1 has an issue with FireFTP.  After clicking the "404 Bookmarks" icon the new html page opens for a second then it changes to the FireFTP inferface (chrome://fireftp/content/fireftp.xul).  After closing that that tab the GET request are still sending in the background.

If I hit back it does go back to the 404 Bookmarks html, but then immediately goes to FireFTP.

**Comment by evilpie** [comment]
Thanks for reporting this issue!
Sadly I can't reproduce this after installing FireFTP on Firefox 51 or Firefox 54. I have a slight suspicion that FireFTP is somehow handling my `tabs.create({url: "/index.html"})` call.

**Comment by Pheil** [comment]
Weird, I thought for sure the issue could be duplicated.  I also failed to duplicate in FF53.  The original issue was with FF52.0b8.

Your "tabs.create" works fine.  My first assumption was that I had FireFTP bookmarked, but I don't see one anywhere.  I'll try to duplicate with a clean profile on FF52
