### ISSUE TITLE
This could be my most useful addon yet, but...(LOL)

### ISSUE THREAD

**Issue by originalpizamoto** [evilpie/404-bookmarks#10]
Is there a way you could just check the base url, i.e. www.GitHub.com, and skip the addended portion i.e. www.GitHub.com/evilpie/404-/bookmarks/issues/new . Please, please, please... oh, wait that's a James Brown song. LOL

Thanks so much...

**Comment by evilpie** [comment]
This doesn't sound like a useful feature to me.
