### ISSUE TITLE
not installing!!!

### ISSUE THREAD

**Issue by MacgyverJohnson** [evilpie/404-bookmarks#2]
Hello there @evilpie 
Extension is stuck at installing..using FF 49 32 bit windows 8.1.pro x64 ..tried saving the xpi file `404_bookmarks-1.0-an+fx.xpi` but still does not work...? I noticed there is no install.rdf file inside the extension...? in about:addons page it shows downloading which cannot be cancelled....can i generate any log file to give more feedback?
Only way I could install addon was to temporarily load addon from about:debugging even  then it did 
![screenshot 469](https://cloud.githubusercontent.com/assets/17729946/24286705/8e7ef298-10a0-11e7-8335-8f213d072902.png)
not work(icon appeared on toolbar but did not show anything 
Best Regards
(tested on clean ff profile as well with no luck) :(

**Comment by evilpie** [comment]
Please install the addon from addons.mozilla.org, because you seem to have an outdated version. As you can also see on AMO, this addon is only compatible with Firefox 51+, you are running an outdated version.
