### ISSUE TITLE
URLs mistakenly flagged

### ISSUE THREAD

**Issue by Dennywuh** [evilpie/404-bookmarks#5]
Hi Tom,
I'm replying to a request to list URLs that have been flagged by 404 Bookmarks as expired but that work fine.
 · http://dekopalace.com/store/
 · https://soundcloud.com/stream
 · https://www.reddit.com/r/Documentaries/
 · https://www.reddit.com/r/WILTY/
 · https://www.bellazon.com/main/topic/21107-helen-lindes/
 · https://twitter.com/search?q=%22***%22  (where *** is any search parameter)
 · https://twitter.com/***  (where *** is my Twitter username)

I hope this is of use. Regards.

**Comment by evilpie** [comment]
Thank you so much for reporting this issue here! Sadly, I can't reproduce it.
![screenshot from 2017-11-19 20-02-45](https://user-images.githubusercontent.com/296445/32994251-c2a53de4-cd64-11e7-8d67-81d675f6f87e.png)
As you can see I bookmarked your pages and none show up as expired. What text is inside the parentheses _()_ after the links?

**Comment by Dennywuh** [comment]
The **Expired bookmarks** and **Other bookmarks** headings are new since I last uninstalled the extension.
I hope this helps:
![404bookmarks](https://user-images.githubusercontent.com/33808978/32994757-2d0d8798-cd6c-11e7-941c-92202c061ca4.jpg)

**Comment by evilpie** [comment]
Very strange indeed. Do you have some VPN or local proxy? Can you try disabling every other extension?

**Comment by Dennywuh** [comment]
I have a direct fibre optic connection, no VPN, no proxy, no firewall other than Windows Defender.  I do keep my Hosts file updated from http://winhelp2002.mvps.org/hosts.htm but I can connect to those sites without a problem, so that's not it.
Some of the sites I blanked in the uploaded image are Facebook URLs. I intentionally block facebook.com, facebook.net and fbcdn.com with uBlock Origin, so I expect them to be unreachable.
I've disabled all other add-ons, restarted and tried again and now the Facebook links work but the others still appear in the **Other bookmarks** list, except www.bellazon.com, that's not there anymore.

**Comment by evilpie** [comment]
Yeah sorry, seems like other extensions are at least partly to blame. What version of Firefox are you using?

**Comment by Dennywuh** [comment]
Firefox Quantum 57.0 (64-bit).
I'm sorry, I don't think other extensions are involved. When I disabled them all except 404 Bookmarks nothing changed, apart from the Facebook URLs becoming available because the uBlock Origin extension that usually blocks them was disabled.
I'm finding that some links are flagged as not-working only temporarily. Bellazon.com, for instance, only appeared once, early on. Since then various others have turned up on the list once and never again.

**Comment by evilpie** [comment]
Maybe I just need to add some code to retry those URLs a few times.
