### ISSUE TITLE
404 Bookmarks not at addons.mozilla.org

### ISSUE THREAD

**Issue by 13regent** [evilpie/404-bookmarks#6]
Hi,
Why isnt 404 Bookmarks found at addons.mozilla.org? When I go to the page below I get the message "Page not found"

https://addons.mozilla.org/en-US/firefox/addon/404-bookmarks/

Whats up?

**Comment by evilpie** [comment]
The extension was temporarily disabled by Mozilla, because apparently the description wasn't simple enough.
